### ISSUE TITLE
Set the application name with a parameter

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvistaqt#50]
I think it would nice to have a way to modify the Qt application name with a parameter from `BackgroundPlotter`. For example: `app_name`.

This could prevent [creating a full `QApplication`](https://github.com/mne-tools/mne-python/pull/8117/files#diff-7d015438f1f32b2f4c28f713c2e3e7b1R91) or [using `setApplicationName()`](https://doc.qt.io/qt-5/qcoreapplication.html#applicationName-prop) afterwards.

**Comment by larsoner** [comment]
-1 on wrappnig things that are trivial to do directly in Qt. To me doing `setApplicationName` is easy enough, it already accepts a string. The only reason I see to have `set_icon` rather than using builtin Qt functions is that we can actually do some processing to make it easier by accepting ndarray, triaging the format, etc.
