### ISSUE TITLE
The Brief Example in the doc does not work as expected.

### ISSUE THREAD

**Issue by szsdk** [pyvista/pyvistaqt#74]
The example from the doc does not show anything unless this sentence
```python
plotter.app.exec_()
```
is added.

Maybe this line is omitted deliberately. But I would love to see some explanatory comments which would help other new people like me a lot.

**Comment by akaszynski** [comment]
I think it matters if the example is being run from a script or not.  Were you running it as a script or interactively?

**Comment by szsdk** [comment]
Yeah, I run it as a script.

**Comment by akaszynski** [comment]
That's the issue then.  The `BackgroundPlotter` isn't designed to be a "blocking" operation.  This means that as soon as the main Python thread exits, it will kill the plotter as well.  When you use `plotter.app.exec_()`, it makes it a blocking operation, which stops the script from exiting until the plotter has exited.

We should indeed add this behavior to the docs.  @GuillaumeFavelier, think you could add it at some point in the future?  Otherwise, I can submit a PR later.
`

**Comment by GuillaumeFavelier** [comment]
Reminds me of https://github.com/pyvista/pyvista-support/issues/262

I'm on it!
