### ISSUE TITLE
How to set "off_screen" totally?

### ISSUE THREAD

**Issue by szsdk** [pyvista/pyvistaqt#84]
I have a project depending on this wonderful project. Now I want to add some tests to my project. They are supposed to run automatically without a screen. I tried to set off_screen of BackGroundPlotter to True. But I found that this line 
https://github.com/pyvista/pyvistaqt/blob/239a237a555fb2800273f6099509f056d7042052/pyvistaqt/plotting.py#L273
always gets running. Is it a bug or feature? If it is a feature, is there any workaround? Thanks.

**Comment by GuillaumeFavelier** [comment]
First off it's called `off_screen` but there might be a better name for it. AFAIK, except if VTK itself is built to support this feature (for example `osmesa`: https://discourse.vtk.org/t/offscreen-rendering-opening-window/1660/2, https://discourse.vtk.org/t/black-image-when-using-offscreen-rendering-inside-qt-application/3935), a "screen" will be needed. This screen can be virtual that's why our CIs on Linux use `xvfb` for instance.

So `off_screen=True` in `pyvistaqt` is more about "rendering without opening a window". Also from my experience, this mode has [limitations](https://github.com/mne-tools/mne-python/pull/8602) but I can investigate further if necessary.

Now back on your question, I don't quite understand the link between `off_screen` and `view_isometric`. The latter just [set the default camera parameters](https://docs.pyvista.org/plotting/plotting.html?highlight=isometric#pyvista.BasePlotter.view_isometric). Those can be modified exactly like the vanilla `Plotter` in PyVista by playing with the `camera` attribute. Do you have an issue with it?

**Comment by szsdk** [comment]
> So `off_screen=True` in `pyvistaqt` is more about "rendering without opening a window". Also from my experience, this mode has limitations but I can investigate further if necessary.

Now, I have a better understanding about the `off_screen` flag. In the beginning, The `update` method of `BasePlotter`

https://github.com/pyvista/pyvista/blob/fbb8570ebd942cdb82a0602daf78a8dff9e2c972/pyvista/plotting/plotting.py#L1166-L1180

gives me a wrong idea that `off_screen` is used for avoiding rendering. And this is why I found it a little bit strange when I saw `view_isometric` triggers a rendering at

https://github.com/pyvista/pyvista/blob/fbb8570ebd942cdb82a0602daf78a8dff9e2c972/pyvista/plotting/plotting.py#L836-L843

**Comment by GuillaumeFavelier** [comment]
Good catch.

So when `off_screen=True`, the `update()` function is disabled because it depends on an internal attribute called `self.iren` (of type `vtkRenderWindowInteractor`) which is not initialized. This is arguably the limitation I'm talking about in https://github.com/mne-tools/mne-python/pull/8602#issuecomment-738033391.

But the rendering window itself (attribute `self.ren_win` of type `vtkRenderWindow`) can still be used for rendering.

I hope what I say is not too confusing, sorry for going into details.

**Comment by szsdk** [comment]
Thanks for your detailed explanation. I am doing some development on a remote server. Sadly, My Mac does not cooperate well with it. And I cannot make pyvistaqt work through ssh. So I hope I could run some off screen test at least. But now it seems to be another died end. So according to your link, there would be a big refactor of pysitaqt?

**Comment by szsdk** [comment]
Please feel free to close this issue.

**Comment by GuillaumeFavelier** [comment]
>  So according to your link, there would be a big refactor of pysitaqt?

No this part is not related to `pyvistaqt` sorry :sweat_smile:
